config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :fundraisers
  resources :charges

  get 'about' => 'home#about'
  get 'contact' => 'home#contact'

  get 'faq' => 'high_voltage/pages#show', id: 'faq'
  get 'privacy_policy' => 'high_voltage/pages#show', id: 'privacy_policy'
  get 'terms_of_use' => 'high_voltage/pages#show', id: 'terms_of_use'

end

app/models/fundraiser.rb
# == Schema Information
#
# Table name: fundraisers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  summary    :text(65535)
#  goal       :integer          default(0), not null
#  currency   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  image_id   :string(255)
#  active     :boolean          default(TRUE)
#
# Indexes
#
#  index_fundraisers_on_user_id  (user_id)
#

class Fundraiser < ActiveRecord::Base
  belongs_to :user
  has_many :donations
  has_many :posts, dependent: :destroy

  attachment :image, type: :image

  validates :name, presence: true
  validates :summary, presence: true
  validates :goal, presence: true, numericality: { greater_than: 0 }
  validates :currency, presence: true
  # validates :user_id, presence: true
  validates :image, presence: true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  before_destroy { self.image.delete }

  def amount_collected
    # self.valid_donations.map(&:amount).sum.round
    self.valid_donations.map(&:processing_amount).sum / 100
  end

  def user_full_name
    self.user.full_name if user
  end

  def to_param
    "#{self.id}-#{self.name}".parameterize
  end

  def valid_donations
    self.donations.where(state: 'finished').order(created_at: :desc)
  end
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_fundraiser, only: [:show, :edit, :update, :destroy]

  # GET /fundraisers
  # GET /fundraisers.json
  def index
    @fundraisers = Fundraiser.active.order(created_at: :desc)
    @fundraisers_inactive = Fundraiser.inactive.order(created_at: :desc)
    Activity.create_activity(request, params, current_user, nil)
  end

  # GET /fundraisers/1
  # GET /fundraisers/1.json
  def show
    Activity.create_activity(request, params, current_user, @fundraiser.id)
  end

  # GET /fundraisers/new
  def new
    @fundraiser = Fundraiser.new
  end

  # GET /fundraisers/1/edit
  def edit
    authorize! :manage, @fundraiser
  end

  # POST /fundraisers
  # POST /fundraisers.json
  def create
    @fundraiser = Fundraiser.new(fundraiser_params)
    @fundraiser.currency = 'USD'
    @fundraiser.user_id = current_user.id if current_user

    respond_to do |format|
      if @fundraiser.save
        Activity.create_activity(request, params, current_user, @fundraiser.id)

        if current_user
          format.html { redirect_to @fundraiser, notice: 'Fundraiser was successfully created.' }
        else
          format.html { redirect_to signup_path(fundraiser_id: @fundraiser.id) }
          format.json { render :show, status: :created, location: @fundraiser }
        end
      else
        format.html { render :new }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fundraisers/1
  # PATCH/PUT /fundraisers/1.json
  def update
    authorize! :manage, @fundraiser
    respond_to do |format|
      if @fundraiser.update(fundraiser_params)
        format.html { redirect_to @fundraiser, notice: 'Fundraiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @fundraiser }
      else
        format.html { render :edit }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundraisers/1
  # DELETE /fundraisers/1.json
  def destroy
    authorize! :manage, @fundraiser
    @fundraiser.destroy
    respond_to do |format|
      format.html { redirect_to fundraisers_url, notice: 'Fundraiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fundraiser
      @fundraiser = Fundraiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fundraiser_params
      params.require(:fundraiser).permit(:name, :summary, :goal, :image, :remove_image)
    end
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/views/fundraisers/_created_by.html.erb
<div class="panel panel-default panel_custom">
  <div class="panel-body">
    <div id="created_by">
      Created by <strong><%= @fundraiser.user_full_name %></strong>
      <br />
      on: <%= @fundraiser.created_at.strftime("%B %d, %Y") %>
    </div>
  </div>
</div>

app/views/fundraisers/_donations_list.html.erb
<div id="fundraiser_donations_list">
  <div class="panel panel-default panel_custom">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @fundraiser.valid_donations.count %> Donations</h3>
    </div>
    <table class="table">
      <tbody>
        <% @fundraiser.valid_donations.each do |donation| %>
          <tr id="donation_detail_<%= donation.id %>">
            <td>
              <span class="donation_amount">
                <%= display_donation_amount(donation) %>
              </span>
              <%= donation_amount_in_usd(donation) %>

              <div class='donor-name'>
                <%= display_donation_name(donation) %>
              </div>

              <div class='donor-comment'>
                <%= display_donation_comment(donation) %>
              </div>

              <div class='donor-time'>
                <%= time_ago_in_words(donation.created_at) %> ago
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/fundraisers/_form.html.erb
<%= simple_form_for(@fundraiser) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :summary, input_html: { rows: 5 } %>
    <%= f.input :goal %>

    <%= f.attachment_field :image, direct: true, presigned: true %><br />

    <% if @fundraiser.image_id %>
      <%= image_tag attachment_url(@fundraiser, :image, :fill, 100, 100) %>
      <%= f.check_box :remove_image %>
      <%= f.label :remove_image %>
    <% end %>
  </div>

  <br />

  <div class="form-actions">
    <% button_text = @fundraiser.new_record? ? "Start Fundraiser" : "Update Fundraiser" %>
    <%= f.button :submit, button_text, class: "btn btn-success" %>
  </div>
<% end %>

app/views/fundraisers/_make_donation.html.erb
<div class="panel panel-default panel_custom">
  <div class="panel-heading">
    Location, US
  </div>
  <div class="panel-body">
    <div id="fundraiser_stats">
      <span id="amount_collected">
        <%= number_to_currency(@fundraiser.amount_collected, precision: 0) %>
      </span>
      <span id="amount_goal">
        of <%= number_to_currency(@fundraiser.goal.round, precision: 0) %>
      </span>
      <div id="raised_by">
        Raised by <%= @fundraiser.valid_donations.count %> people
      </div>

      <br />
      <% if @fundraiser.active? %>
        <%= link_to "Make A Donation", new_charge_path(fundraiser_id: get_id(params[:id])), class: "btn btn-primary btn-block btn-lg fundraiser_donation_btn" %>
      <% else %>
        <%= link_to "Not Accepting Donations", '', class: 'btn btn-primary btn-block btn-lg disabled' %>
      <% end %>
      <br />

      Please share on: <div class="addthis_sharing_toolbox"></div>

    </div>
  </div>
</div>

app/views/fundraisers/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<h1>Editing Fundraiser</h1>

<%= render 'form' %>

<%= link_to 'Show', @fundraiser %> |
<%= link_to 'Back', fundraisers_path %>

  </div>
</div>

app/views/fundraisers/index.html.erb
<% provide(:title, "Fundraisers") %>

<p id="notice"><%= notice %></p>

<%= link_to 'Start A Fundraiser', new_fundraiser_path, class: "btn btn-success btn-lg" %>

<% if @fundraisers.present? %>
  <h1>Current Fundraisers</h1>

  <div class="row">

    <% @fundraisers.each do |fundraiser| %>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(attachment_url(fundraiser, :image, :fill, 200, 200)), fundraiser_path(fundraiser) %>
          <div class="caption">
            <h4><%= link_to fundraiser.name, fundraiser_path(fundraiser) %></h4>
            <p>Raised: <%= number_to_currency(fundraiser.amount_collected, precision: 0) %>
            of <%= number_to_currency(fundraiser.goal, precision: 0) %></p>
          </div>
        </div>
      </div>

    <% end %>
  </div>
<% else %>
  <p>No active fundraisers</p>
<% end %>

<% if @fundraisers_inactive.present? %>
  <h1>Past Fundraisers</h1>

  <div class="row">

    <% @fundraisers_inactive.each do |fundraiser| %>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(attachment_url(fundraiser, :image, :fill, 200, 200)), fundraiser_path(fundraiser) %>
          <div class="caption">
            <h4><%= link_to fundraiser.name, fundraiser_path(fundraiser) %></h4>
            <p>Raised: <%= number_to_currency(fundraiser.amount_collected, precision: 0) %>
            of <%= number_to_currency(fundraiser.goal, precision: 0) %></p>
          </div>
        </div>
      </div>

    <% end %>
  </div>
<% end %>

app/views/fundraisers/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<h1>New Fundraiser</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', fundraisers_path %>

  </div>
</div>

app/views/fundraisers/show.html.erb
<% provide(:title, @fundraiser.name) %>

<br />

<div class="well fundraiser_well">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <% if can? :update, @fundraiser %>
        <%= link_to 'Edit Fundraiser', edit_fundraiser_path(@fundraiser), class: "btn btn-success btn-xs pull-right" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <% if can? :update, @fundraiser %>
        <br />
        <%= link_to 'Post Update', new_post_path(fundraiser_id: @fundraiser.id), class: "btn btn-success btn-xs pull-right" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div id="fundraiser_show_name">
        <%= @fundraiser.name %>
      </div>
    </div>
  </div>
  <br />

  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
      <div id="fundraiser_image">
        <div id="fundraiser_main_image">
          <div class="panel panel-default panel_custom">
            <div class="panel-body">
              <%= image_tag attachment_url(@fundraiser, :image, :fill, 700, 500) %>
            </div>
          </div>
        </div>

        <div id="fundraiser_content">
          <div id="fundraiser_summary">
            <div class="panel panel-default panel_custom">
              <div class="panel-body">
                <%= show_line_breaks @fundraiser.summary %>
              </div>
            </div>
          </div>
        </div>

        <div class='visible-xs'>
          <%= render 'make_donation' %>
          <%= render 'created_by' %>
        </div>

        <br />
        <%= render @fundraiser.posts %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4" id="right_side">
      <%= render 'make_donation' %>
      <%= render 'created_by' %>
      <%= render 'donations_list' %>
    </div>
  </div>

  <br />
  <h2>Comments</h2>
  <hr>

  <%= content_tag :div, '',
    class: "fb-comments",
    "data-href" => request.original_url,
    "data-numposts" => "5",
    "data-colorscheme" => "light" %>

</div>