config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :fundraisers
  resources :charges

  get 'about' => 'home#about'
  get 'contact' => 'home#contact'

  get 'faq' => 'high_voltage/pages#show', id: 'faq'
  get 'privacy_policy' => 'high_voltage/pages#show', id: 'privacy_policy'
  get 'terms_of_use' => 'high_voltage/pages#show', id: 'terms_of_use'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    fundraiser = Fundraiser.find(params[:fundraiser_id])
    Activity.create_activity(request, params, current_user, fundraiser.id)
  end

  def create
    validate_params_for_pci

    @fundraiser = Fundraiser.find(params[:fundraiser_id])
    Activity.create_activity(request, params, current_user, @fundraiser.id)

    hide_name = (params[:hideName] == "on") ? true : false
    hide_amount = (params[:hideAmount] == "on") ? true : false
    currency = params[:currency]

    donation = Donation.create(
                 amount: params[:donationAmount],
                 currency: currency.downcase,
                 recurring: false,
                 fundraiser_id: params[:fundraiser_id],
                 first_name: params[:firstName],
                 last_name: params[:lastName],
                 email: params[:email],
                 stripe_token: params[:stripeToken],
                 hide_name: hide_name,
                 hide_amount: hide_amount,
                 comment: params[:comment]
               )

    donation.process_customer!
    donation.process_charge!

    if donation.finished?
      UserMailer.donation_completed(donation.id).deliver_now
      UserMailer.notify_fundraiser_organizer(donation.id).deliver_now
      redirect_to fundraiser_path(@fundraiser), notice: "Thank you for your donation of #{donation.currency.upcase} #{donation.amount}."
    else
      flash.now[:error] = "Something went wrong. Your payment was not processed."
      render 'new'
    end
  rescue Stripe::CardError => e
    puts "in method: #{__method__}, line: #{__LINE__}, exception: #{e.inspect}"
    flash[:error] = e.message
    redirect_to fundraiser_path(@fundraiser), notice: "Something went wrong. Your payment was not processed. Error: #{e.inspect}"
  rescue Exception => e
    puts "in method: #{__method__}, line: #{__LINE__}, exception: #{e.inspect}"
    flash[:error] = e.message
    redirect_to fundraiser_path(@fundraiser), notice: "Something went wrong. Your payment was not processed. Error: #{e.inspect}"
  end

  private

  def description
    desc = ""
    desc += "#{params[:first_name]} #{params[:last_name]}"

    desc
  end

  def validate_params_for_pci
    raise "credit card hitting server" if params.inspect =~ /4242/ && Rails.env.test?
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<% provide(:title, "Payment") %>

<script type="text/javascript">
  Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
</script>

<div class="row">
  <div class="col-xs-12 col-md-5">

    <br />
    <%= form_tag charges_path(fundraiser_id: params[:fundraiser_id]), id: "payment-form" do %>
      <span class="payment-errors"></span>

      <div class="panel panel-default panel_custom">
        <div class="panel-heading">
          <div class="row" >
            <h3 class="panel-title" style="padding-left: 20px">Donation Amount</h3>
          </div>
        </div> <!-- Donation Amount PANEL HEADING END -->

        <div class="panel-body">
          <div class="row" style="margin-bottom: 0px;">
            <div class="col-xs-12">
              <div class="form-group">
                <!-- <div class="col-lg-10"> -->
                  <div class="form-inline" style="margin-bottom: 0px;">
                    <div class="col-xs-3 col-sm-2 col-md-2" style="padding-left: 0px; padding-right: 2px;">
                      <%= select_tag :currency,
                            options_for_select(Donation::SUPPORTED_CURRENCIES.map(&:upcase)),
                            include_blank: false,
                            class: "form-control xcol-sm-2" %>
                    </div>
                    <div class="col-xs-9 col-sm-10 col-md-10" style="padding-left: 0px; padding-right: 0px;">
                      <div class='input-group'>
                        <input
                            type="tel"
                            class="form-control xinput-group-addon"
                            name="donationAmount"
                            placeholder="Donation Amount"
                            required autofocus
                        />
                        <div class="input-group-addon">.00</div>
                      </div>
                    </div>

                  </div>
                <!-- </div> -->
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12">
              <div class="checkbox checkbox_div">
                <p class="help-block">$10 is the minimum online donation</p>
                <label>
                  <input type="checkbox" name="hideAmount"/> Hide amount from everyone but the organizer
                </label>
              </div>
            </div>
          </div>
        </div> <!-- Donation Amount PANEL BODY END -->
      </div> <!-- Donation Amount PANEL END -->

      <div class="panel panel-default panel_custom"> <!-- CONTACT DETAILS PANEL START -->
        <div class="panel-heading"> <!-- CONTACT DETAILS PANEL HEADING START -->
          <div class="row" >
            <h3 class="panel-title" style="padding-left: 20px">Contact Details</h3>
          </div>
        </div> <!-- CONTACT DETAILS PANEL HEADING END -->
        <div class="panel-body"> <!-- CONTACT DETAILS PANEL BODY START -->

          <div class="row">
            <div class="col-xs-7 col-md-7">
              <div class="form-group">
                <label for="firstName"><span class="hidden-xs">FIRST NAME</label>
                <input
                  type="text"
                  class="form-control"
                  name="firstName"
                  placeholder="First Name"
                  required
                />
              </div>
            </div>
            <div class="col-xs-5 col-md-5 pull-right">
              <div class="form-group">
                <label for="lastName"><span class="hidden-xs">LAST NAME</label>
                <input
                  type="text"
                  class="form-control"
                  name="lastName"
                  placeholder="Last Name"
                  required
                />
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12 col-md-12">
              <div class="form-group">
                <label for="email"><span class="hidden-xs">EMAIL</label>
                <input
                  type="email"
                  class="form-control"
                  name="email"
                  placeholder="Email"
                  required
                />
              </div>
            </div>
          </div>

          <div class="checkbox checkbox_div">
            <label>
              <input type="checkbox" name="hideName"/> Hide name from everyone but the organizer
            </label>
          </div>

        </div> <!-- CONTACT DETAILS PANEL BODY END -->
      </div> <!-- CONTACT DETAILS PANEL END -->

      <div class="panel panel-default panel_custom credit-card-box"> <!-- CREDIT CARD PANEL START -->
        <div class="panel-heading display-table"> <!-- CREDIT CARD PANEL HEADING START -->
          <div class="row display-tr" >
            <h3 class="panel-title display-td" >Payment Details</h3>
            <div class="display-td" >
              <img class="img-responsive pull-right" src="http://i76.imgup.net/accepted_c22e0.png">
            </div>
          </div>
        </div> <!-- CREDIT CARD PANEL HEADING END -->
        <div class="panel-body"> <!-- CREDIT CARD PANEL BODY START -->

          <div class="row">
            <div class="col-xs-12">
              <div class="form-group">
                <label for="cardNumber">CARD NUMBER</label>
                <div class="input-group">
                  <input
                    type="tel"
                    class="form-control"
                    id="cardNumber"
                    data-stripe="number"
                    placeholder="Valid Card Number"
                    autocomplete="cc-number"
                    required
                  />
                  <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-7 col-md-7">
              <div class="form-group">
                <label for="cardExpiryMM">EXPIRATION (MM/YYYY)</label>

                <div class="row">
                  <div class="col-xs-5 col-md-5">
                    <div class="input-group">
                      <input
                        type="tel"
                        class="form-control"
                        id="cardExpiryMM"
                        data-stripe="exp-month"
                        placeholder="MM"
                        autocomplete="cc-exp"
                        required
                        style="border-radius: 4px;"
                      />
                    </div>
                  </div>
                  <div class="col-xs-5 col-md-5" id="div_card_expiry_yy">
                    <div class="input-group">
                      <input
                        type="tel"
                        class="form-control"
                        id="cardExpiryYYYY"
                        data-stripe="exp-year"
                        placeholder="YYYY"
                        autocomplete="cc-exp"
                        required
                        style="border-radius: 4px;"
                      />
                    </div>
                  </div>
                </div>

              </div>
            </div>
            <div class="col-xs-5 col-md-5 pull-right">
              <div class="form-group">
                <label for="cardCVC">CV CODE</label>
                <input
                  type="tel"
                  class="form-control"
                  id="cardCVC"
                  data-stripe="cvc"
                  placeholder="CVC"
                  autocomplete="cc-csc"
                  required
                />
              </div>
            </div>

          </div>
        </div> <!-- CREDIT CARD PANEL BODY END -->
      </div> <!-- CREDIT CARD PANEL END -->

      <textarea class="form-control" rows="3" name="comment" placeholder="Comment"></textarea><br />

      <button type="submit" class="btn btn-lg btn-success btn-block">Make Donation</button>
    <% end %>

  </div>
</div>