config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :fundraisers
  resources :charges

  get 'about' => 'home#about'
  get 'contact' => 'home#contact'

  get 'faq' => 'high_voltage/pages#show', id: 'faq'
  get 'privacy_policy' => 'high_voltage/pages#show', id: 'privacy_policy'
  get 'terms_of_use' => 'high_voltage/pages#show', id: 'terms_of_use'

end

app/views/layouts/_addthis.html.erb
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53d96ee90d6e0f06"></script>

app/views/layouts/_facebook_sdk_for_javascript.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1007874889256678',
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<hr />
<footer class="text-muted">
  AidACause.org © 2015

  <p class="pull-right">
    <%= link_to "Privacy Policy", page_path('privacy_policy') %> |
    <!-- <%= link_to "Terms of use", page_path('terms_of_use') %> | -->
    <%= link_to "FAQ", page_path('faq') %> |
    <%= link_to "Contact Us", contact_path %> |
    <%= link_to "Back to top", "#" %>
  </p>
</footer>

app/views/layouts/_google_analytics_code.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-92542144-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-92542144-3');
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id='header'>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("aac_logo.png", height: "40px", alt: "AidACause Logo"),
            root_path,
            class: "navbar-brand",
            id: "logo" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Home", root_path %></li> -->
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Fundraisers", fundraisers_path %></li>
        <!-- <li><%= link_to "Contact Us", contact_path %></li> -->

        <% if current_user %>
          <li><a>Logged in as <strong><%= current_user.email %></strong></a></li>
          <li><%= link_to 'Account', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_meta_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"     content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="description"  content="<%= meta_description yield(:description) %>">

<meta property="og:url"         content="<%= url_for(only_path: false) %>">
<meta property="og:type"        content="website">
<meta property="og:title"       content="<%= yield(:title) %>">
<!-- <meta property="og:image"       content="<%#= ApplicationHelper::SITE_URL %>/assets/tl1.png"> -->
<meta property="og:description" content="<%= meta_description yield(:description) %>">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/google_analytics_code' %>
  <title><%= yield(:title) %> | Aid A Cause</title>
  <%= render 'layouts/meta_tags' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</head>
<body data-no-turbolink='true'>
  <%= render "layouts/facebook_sdk_for_javascript" %>
  <%= render "layouts/header" %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-md-offset-1">

        <%= render "layouts/flash_message" %>
        <%= yield %>
        <%= render "layouts/footer" %>

      </div>
    </div>
  </div>
  <%= render "layouts/addthis" %>
</body>
</html>